### ISSUE TITLE
Change light pink with comp green

### ISSUE THREAD

**Issue by reconwhispers** [KidSysco/nfty-stays-web#14]

**Comment by boristotle** [comment]
@reconwhispers where do you want this changed?

**Comment by boristotle** [comment]
do you have the hex value for the green color you want? i don't see this in the color scheme for nfty stays

**Comment by KidSysco** [comment]
I do not, I think Josh just said to pick a nice green that looks good with black text on it.

**Comment by reconwhispers** [comment]
what do you think about one of these:
complementary to nfty pink - 1EEB8F
split complementary- 1EEB4A
triadic- 7AEB1E


here are the 2 places to change:
![image](https://user-images.githubusercontent.com/97454558/165830645-f91a5c7e-fbc0-4cc0-a01b-f2dcb2288ed4.png)
![image](https://user-images.githubusercontent.com/97454558/165830713-90047ed2-e721-4e3a-99c9-e5bd2e7a3fa6.png)
