### ISSUE TITLE
Change "NFTy Stays Pitch Deck"

### ISSUE THREAD

**Issue by reconwhispers** [KidSysco/nfty-stays-web#20]
Change "NFTy Stays Pitch Deck" to "NFTy Stays Guest Experience" 
Update the pdf to this one with grammar and content corrections - in discord

![image
[NFTY STAYS DECK.pdf](https://github.com/KidSysco/nfty-stays-web/files/8587279/NFTY.STAYS.DECK.pdf)
](https://user-images.githubusercontent.com/97454558/165860330-1a57f3fb-84fb-4f5f-8797-e0e91a42bac9.png)

**Comment by KidSysco** [comment]
https://rumble.com/v12tuxz-time-lapse-of-stay-nfty-by-tjsart.html

**Comment by reconwhispers** [comment]
[NFTY STAYS DECK.pdf](https://github.com/KidSysco/nfty-stays-web/files/8597433/NFTY.STAYS.DECK.pdf)

**Comment by KidSysco** [comment]
Awesome, this has been updated!
